// <auto-generated />
using System;
using DailyTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506125455_AddActivities")]
    partial class AddActivities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DailyTracker.API.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("DailyTracker.API.Models.DSAProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSolved")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateSolved");

                    b.HasIndex("Difficulty");

                    b.ToTable("DSAProblems", (string)null);
                });

            modelBuilder.Entity("DailyTracker.API.Models.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyLogs", (string)null);
                });

            modelBuilder.Entity("DailyTracker.API.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsCompleted");

                    b.ToTable("Topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5027),
                            IsCompleted = false,
                            Name = "Component architecture and communication"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5031),
                            IsCompleted = false,
                            Name = "Data binding (one-way, two-way, event binding)"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5033),
                            IsCompleted = false,
                            Name = "Lifecycle hooks and when they run"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5035),
                            IsCompleted = false,
                            Name = "Services and dependency injection"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5037),
                            IsCompleted = false,
                            Name = "Observables vs promises"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5040),
                            IsCompleted = false,
                            Name = "HTTP client and API integration"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5041),
                            IsCompleted = false,
                            Name = "Routing and navigation"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5043),
                            IsCompleted = false,
                            Name = "Route parameters and guards"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5044),
                            IsCompleted = false,
                            Name = "Reactive vs template-driven forms"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5047),
                            IsCompleted = false,
                            Name = "Form validation"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5048),
                            IsCompleted = false,
                            Name = "Change detection basics"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5049),
                            IsCompleted = false,
                            Name = "Lazy loading modules"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5051),
                            IsCompleted = false,
                            Name = "Error handling in API calls"
                        },
                        new
                        {
                            Id = 14,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5052),
                            IsCompleted = false,
                            Name = "REST API fundamentals"
                        },
                        new
                        {
                            Id = 15,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5054),
                            IsCompleted = false,
                            Name = "HTTP verbs and status codes"
                        },
                        new
                        {
                            Id = 16,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5055),
                            IsCompleted = false,
                            Name = "Controllers and routing"
                        },
                        new
                        {
                            Id = 17,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5057),
                            IsCompleted = false,
                            Name = "Model binding"
                        },
                        new
                        {
                            Id = 18,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5059),
                            IsCompleted = false,
                            Name = "Dependency injection"
                        },
                        new
                        {
                            Id = 19,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5060),
                            IsCompleted = false,
                            Name = "Layered architecture (controller/service/repository)"
                        },
                        new
                        {
                            Id = 20,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5062),
                            IsCompleted = false,
                            Name = "CRUD operations"
                        },
                        new
                        {
                            Id = 21,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5063),
                            IsCompleted = false,
                            Name = "Async/await usage"
                        },
                        new
                        {
                            Id = 22,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5064),
                            IsCompleted = false,
                            Name = "Exception handling"
                        },
                        new
                        {
                            Id = 23,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5066),
                            IsCompleted = false,
                            Name = "DTO usage"
                        },
                        new
                        {
                            Id = 24,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5067),
                            IsCompleted = false,
                            Name = "Authentication basics (JWT flow)"
                        },
                        new
                        {
                            Id = 25,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5068),
                            IsCompleted = false,
                            Name = "Validation"
                        },
                        new
                        {
                            Id = 26,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5070),
                            IsCompleted = false,
                            Name = "Database integration (EF/ADO.NET basics)"
                        },
                        new
                        {
                            Id = 27,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5071),
                            IsCompleted = false,
                            Name = "SELECT queries"
                        },
                        new
                        {
                            Id = 28,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5072),
                            IsCompleted = false,
                            Name = "WHERE filtering"
                        },
                        new
                        {
                            Id = 29,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5074),
                            IsCompleted = false,
                            Name = "ORDER BY"
                        },
                        new
                        {
                            Id = 30,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5075),
                            IsCompleted = false,
                            Name = "GROUP BY"
                        },
                        new
                        {
                            Id = 31,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5077),
                            IsCompleted = false,
                            Name = "Aggregate functions (COUNT, SUM, AVG)"
                        },
                        new
                        {
                            Id = 32,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5078),
                            IsCompleted = false,
                            Name = "JOINS"
                        },
                        new
                        {
                            Id = 33,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5079),
                            IsCompleted = false,
                            Name = "Primary and foreign keys"
                        },
                        new
                        {
                            Id = 34,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5081),
                            IsCompleted = false,
                            Name = "Basic indexing concept"
                        },
                        new
                        {
                            Id = 35,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5083),
                            IsCompleted = false,
                            Name = "Stored procedures basics"
                        },
                        new
                        {
                            Id = 36,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 5, 6, 12, 54, 54, 129, DateTimeKind.Utc).AddTicks(5084),
                            IsCompleted = false,
                            Name = "Insert/update/delete operations"
                        });
                });

            modelBuilder.Entity("DailyTracker.API.Models.Activity", b =>
                {
                    b.HasOne("DailyTracker.API.Models.DailyLog", "DailyLog")
                        .WithMany("Activities")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("DailyTracker.API.Models.DailyLog", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
