// <auto-generated />
using System;
using DailyTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427133704_AddTopics")]
    partial class AddTopics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DailyTracker.API.Models.DSAProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSolved")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateSolved");

                    b.HasIndex("Difficulty");

                    b.ToTable("DSAProblems", (string)null);
                });

            modelBuilder.Entity("DailyTracker.API.Models.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DSA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyLogs", (string)null);
                });

            modelBuilder.Entity("DailyTracker.API.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsCompleted");

                    b.ToTable("Topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5445),
                            IsCompleted = false,
                            Name = "Component architecture and communication"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5449),
                            IsCompleted = false,
                            Name = "Data binding (one-way, two-way, event binding)"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5451),
                            IsCompleted = false,
                            Name = "Lifecycle hooks and when they run"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5452),
                            IsCompleted = false,
                            Name = "Services and dependency injection"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5453),
                            IsCompleted = false,
                            Name = "Observables vs promises"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5456),
                            IsCompleted = false,
                            Name = "HTTP client and API integration"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5457),
                            IsCompleted = false,
                            Name = "Routing and navigation"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5458),
                            IsCompleted = false,
                            Name = "Route parameters and guards"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5459),
                            IsCompleted = false,
                            Name = "Reactive vs template-driven forms"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5461),
                            IsCompleted = false,
                            Name = "Form validation"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5462),
                            IsCompleted = false,
                            Name = "Change detection basics"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5463),
                            IsCompleted = false,
                            Name = "Lazy loading modules"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Angular",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5465),
                            IsCompleted = false,
                            Name = "Error handling in API calls"
                        },
                        new
                        {
                            Id = 14,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5466),
                            IsCompleted = false,
                            Name = "REST API fundamentals"
                        },
                        new
                        {
                            Id = 15,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5467),
                            IsCompleted = false,
                            Name = "HTTP verbs and status codes"
                        },
                        new
                        {
                            Id = 16,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5469),
                            IsCompleted = false,
                            Name = "Controllers and routing"
                        },
                        new
                        {
                            Id = 17,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5470),
                            IsCompleted = false,
                            Name = "Model binding"
                        },
                        new
                        {
                            Id = 18,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5472),
                            IsCompleted = false,
                            Name = "Dependency injection"
                        },
                        new
                        {
                            Id = 19,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5473),
                            IsCompleted = false,
                            Name = "Layered architecture (controller/service/repository)"
                        },
                        new
                        {
                            Id = 20,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5474),
                            IsCompleted = false,
                            Name = "CRUD operations"
                        },
                        new
                        {
                            Id = 21,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5475),
                            IsCompleted = false,
                            Name = "Async/await usage"
                        },
                        new
                        {
                            Id = 22,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5476),
                            IsCompleted = false,
                            Name = "Exception handling"
                        },
                        new
                        {
                            Id = 23,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5477),
                            IsCompleted = false,
                            Name = "DTO usage"
                        },
                        new
                        {
                            Id = 24,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5478),
                            IsCompleted = false,
                            Name = "Authentication basics (JWT flow)"
                        },
                        new
                        {
                            Id = 25,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5479),
                            IsCompleted = false,
                            Name = "Validation"
                        },
                        new
                        {
                            Id = 26,
                            Category = ".NET",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5481),
                            IsCompleted = false,
                            Name = "Database integration (EF/ADO.NET basics)"
                        },
                        new
                        {
                            Id = 27,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5482),
                            IsCompleted = false,
                            Name = "SELECT queries"
                        },
                        new
                        {
                            Id = 28,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5483),
                            IsCompleted = false,
                            Name = "WHERE filtering"
                        },
                        new
                        {
                            Id = 29,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5484),
                            IsCompleted = false,
                            Name = "ORDER BY"
                        },
                        new
                        {
                            Id = 30,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5485),
                            IsCompleted = false,
                            Name = "GROUP BY"
                        },
                        new
                        {
                            Id = 31,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5486),
                            IsCompleted = false,
                            Name = "Aggregate functions (COUNT, SUM, AVG)"
                        },
                        new
                        {
                            Id = 32,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5520),
                            IsCompleted = false,
                            Name = "JOINS"
                        },
                        new
                        {
                            Id = 33,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5521),
                            IsCompleted = false,
                            Name = "Primary and foreign keys"
                        },
                        new
                        {
                            Id = 34,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5523),
                            IsCompleted = false,
                            Name = "Basic indexing concept"
                        },
                        new
                        {
                            Id = 35,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5524),
                            IsCompleted = false,
                            Name = "Stored procedures basics"
                        },
                        new
                        {
                            Id = 36,
                            Category = "SQL",
                            CreatedAt = new DateTime(2026, 4, 27, 13, 37, 3, 567, DateTimeKind.Utc).AddTicks(5525),
                            IsCompleted = false,
                            Name = "Insert/update/delete operations"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
